/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AnalisePrecedenciaOperadores {
    }
    interface AnalisePreditiva {
    }
    interface AppApopasso1 {
        "grammar": string;
    }
    interface AppApopasso2 {
        "grammar": string;
    }
    interface AppApopasso3 {
        "grammar": string;
    }
    interface AppFirst {
        "grammar": string;
    }
    interface AppFollow {
        "grammar": string;
    }
    interface AppHome {
    }
    interface AppPredictionTable {
        "grammarInput": string;
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRecognitionTable {
        "grammar": string;
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAnalisePrecedenciaOperadoresElement extends Components.AnalisePrecedenciaOperadores, HTMLStencilElement {
    }
    var HTMLAnalisePrecedenciaOperadoresElement: {
        prototype: HTMLAnalisePrecedenciaOperadoresElement;
        new (): HTMLAnalisePrecedenciaOperadoresElement;
    };
    interface HTMLAnalisePreditivaElement extends Components.AnalisePreditiva, HTMLStencilElement {
    }
    var HTMLAnalisePreditivaElement: {
        prototype: HTMLAnalisePreditivaElement;
        new (): HTMLAnalisePreditivaElement;
    };
    interface HTMLAppApopasso1Element extends Components.AppApopasso1, HTMLStencilElement {
    }
    var HTMLAppApopasso1Element: {
        prototype: HTMLAppApopasso1Element;
        new (): HTMLAppApopasso1Element;
    };
    interface HTMLAppApopasso2Element extends Components.AppApopasso2, HTMLStencilElement {
    }
    var HTMLAppApopasso2Element: {
        prototype: HTMLAppApopasso2Element;
        new (): HTMLAppApopasso2Element;
    };
    interface HTMLAppApopasso3Element extends Components.AppApopasso3, HTMLStencilElement {
    }
    var HTMLAppApopasso3Element: {
        prototype: HTMLAppApopasso3Element;
        new (): HTMLAppApopasso3Element;
    };
    interface HTMLAppFirstElement extends Components.AppFirst, HTMLStencilElement {
    }
    var HTMLAppFirstElement: {
        prototype: HTMLAppFirstElement;
        new (): HTMLAppFirstElement;
    };
    interface HTMLAppFollowElement extends Components.AppFollow, HTMLStencilElement {
    }
    var HTMLAppFollowElement: {
        prototype: HTMLAppFollowElement;
        new (): HTMLAppFollowElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppPredictionTableElement extends Components.AppPredictionTable, HTMLStencilElement {
    }
    var HTMLAppPredictionTableElement: {
        prototype: HTMLAppPredictionTableElement;
        new (): HTMLAppPredictionTableElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRecognitionTableElement extends Components.AppRecognitionTable, HTMLStencilElement {
    }
    var HTMLAppRecognitionTableElement: {
        prototype: HTMLAppRecognitionTableElement;
        new (): HTMLAppRecognitionTableElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "analise-precedencia-operadores": HTMLAnalisePrecedenciaOperadoresElement;
        "analise-preditiva": HTMLAnalisePreditivaElement;
        "app-apopasso1": HTMLAppApopasso1Element;
        "app-apopasso2": HTMLAppApopasso2Element;
        "app-apopasso3": HTMLAppApopasso3Element;
        "app-first": HTMLAppFirstElement;
        "app-follow": HTMLAppFollowElement;
        "app-home": HTMLAppHomeElement;
        "app-prediction-table": HTMLAppPredictionTableElement;
        "app-profile": HTMLAppProfileElement;
        "app-recognition-table": HTMLAppRecognitionTableElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AnalisePrecedenciaOperadores {
    }
    interface AnalisePreditiva {
    }
    interface AppApopasso1 {
        "grammar"?: string;
    }
    interface AppApopasso2 {
        "grammar"?: string;
    }
    interface AppApopasso3 {
        "grammar"?: string;
    }
    interface AppFirst {
        "grammar"?: string;
    }
    interface AppFollow {
        "grammar"?: string;
    }
    interface AppHome {
    }
    interface AppPredictionTable {
        "grammarInput"?: string;
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRecognitionTable {
        "grammar"?: string;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "analise-precedencia-operadores": AnalisePrecedenciaOperadores;
        "analise-preditiva": AnalisePreditiva;
        "app-apopasso1": AppApopasso1;
        "app-apopasso2": AppApopasso2;
        "app-apopasso3": AppApopasso3;
        "app-first": AppFirst;
        "app-follow": AppFollow;
        "app-home": AppHome;
        "app-prediction-table": AppPredictionTable;
        "app-profile": AppProfile;
        "app-recognition-table": AppRecognitionTable;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "analise-precedencia-operadores": LocalJSX.AnalisePrecedenciaOperadores & JSXBase.HTMLAttributes<HTMLAnalisePrecedenciaOperadoresElement>;
            "analise-preditiva": LocalJSX.AnalisePreditiva & JSXBase.HTMLAttributes<HTMLAnalisePreditivaElement>;
            "app-apopasso1": LocalJSX.AppApopasso1 & JSXBase.HTMLAttributes<HTMLAppApopasso1Element>;
            "app-apopasso2": LocalJSX.AppApopasso2 & JSXBase.HTMLAttributes<HTMLAppApopasso2Element>;
            "app-apopasso3": LocalJSX.AppApopasso3 & JSXBase.HTMLAttributes<HTMLAppApopasso3Element>;
            "app-first": LocalJSX.AppFirst & JSXBase.HTMLAttributes<HTMLAppFirstElement>;
            "app-follow": LocalJSX.AppFollow & JSXBase.HTMLAttributes<HTMLAppFollowElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-prediction-table": LocalJSX.AppPredictionTable & JSXBase.HTMLAttributes<HTMLAppPredictionTableElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-recognition-table": LocalJSX.AppRecognitionTable & JSXBase.HTMLAttributes<HTMLAppRecognitionTableElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
